apiVersion: v1
kind: Service
metadata:
  name: census-api-service
spec:
  selector:
    app: census-api
  ports:
    - protocol: TCP
      port: 8000 # The external port 
      targetPort: 8000 # The container port
  type: LoadBalancer
